#include "../src/model/FSM.h"
#include "../src/model/Transition.h"
#include "../src/parsing/CodeParser.h"
#include <QString>
#include <gtest/gtest.h>

// GTest for User Generated Code Parsing (Config-based)
TEST(UserCodeParsingTest, ParsesGeneratedFSMConfig) {
  QString code = R"(
// Auto-generated FSM Config - MyFSM
// Generated by QtFSM Designer

#include <functional>
#include <iostream>
#include <string>
#include <unordered_map>
#include <vector>

struct TransitionConfig {
    std::string event;
    std::string to;
    std::string guard;
    std::string action;
};

struct StateConfig {
    std::string name;
    double x;
    double y;
    bool isFinal;
    std::string entry;
    std::string exit;
    std::vector<TransitionConfig> transitions;
};

struct FSMConfig {
    std::string initial;
    std::unordered_map<std::string, StateConfig> states;
};

FSMConfig cfg;
cfg.initial = "Init";

cfg.states["Init"] = StateConfig{
    "Init",
    10.00,
    20.00,
    false,
    "enterInit",
    "exitInit",
    {
        {"zattiriko", "Run", "", ""},
    }
};

cfg.states["Run"] = StateConfig{
    "Run",
    100.00,
    200.00,
    false,
    "",
    "",
    {
    }
};
  )";

  CodeParser parser;
  FSM *fsm = parser.parse(code);

  ASSERT_NE(fsm, nullptr)
      << "Should successfully parse user-generated FSM config";

  EXPECT_EQ(fsm->name(), "MyFSM");
  EXPECT_EQ(fsm->states().size(), 2) << "Should have 2 states";

  State *init = fsm->stateById("Init");
  State *run = fsm->stateById("Run");
  ASSERT_NE(init, nullptr);
  ASSERT_NE(run, nullptr);

  EXPECT_TRUE(init->isInitial());
  EXPECT_EQ(init->position().x(), 10.00);
  EXPECT_EQ(init->position().y(), 20.00);
  EXPECT_EQ(init->entryAction(), "enterInit");
  EXPECT_EQ(init->exitAction(), "exitInit");

  // Should have 1 transition from Init to Run
  EXPECT_GT(fsm->transitions().size(), 0)
      << "Should have at least one transition";

  bool foundTransition = false;
  for (Transition *t : fsm->transitions()) {
    if (t->sourceState()->id() == "Init" && t->targetState()->id() == "Run" &&
        t->event() == "zattiriko") {
      foundTransition = true;
      break;
    }
  }

  EXPECT_TRUE(foundTransition)
      << "Should have transition from Init to Run on 'zattiriko' event";

  delete fsm;
}
