// Auto-generated FSM Config - MyFSM
// Generated by QtFSM Designer

#include <functional>
#include <iostream>
#include <string>
#include <unordered_map>
#include <vector>

// --- Simple config structures ---
struct TransitionConfig {
  std::string event;
  std::string to;
  std::string guard;
  std::string action;
};

struct StateConfig {
  std::string name;
  double x;
  double y;
  bool isFinal;
  std::string entry;
  std::string exit;
  std::vector<TransitionConfig> transitions;
};

struct FSMConfig {
  std::string initial;
  std::unordered_map<std::string, StateConfig> states;
};

// --- FSM config instance ---
FSMConfig cfg;
cfg.initial = "Init";

cfg.states["Init"] = StateConfig{
  "Init",
  10.00,
  20.00,
  false,
  "enterInit",
  "exitInit",
  {
    {"zattiriko", "Run", "", ""},
  }
};

cfg.states["Run"] = StateConfig{
  "Run",
  200.00,
  120.00,
  false,
  "",
  "",
  {
  }
};
