// Auto-generated FSM Code - MyFSM
// Generated by QtFSM Designer

#include <memory>
#include <string>

// Event structure
struct Event {
  std::string type;
  // Add your event data here
};

class MyFSMContext;

// Base State class
class MyFSMStateBase {
public:
  virtual ~MyFSMStateBase() = default;

  virtual void onEntry(MyFSMContext *context) {}
  virtual void onExit(MyFSMContext *context) {}
  virtual MyFSMStateBase *handle(MyFSMContext *context, const Event &event) = 0;
  virtual std::string getName() const = 0;
};

// State1 State
class Init : public MyFSMStateBase {
public:
  void onEntry(MyFSMContext *context) override {
    // Entry action for State1
  }

  void onExit(MyFSMContext *context) override {
    // Exit action for State1
  }

  MyFSMStateBase *handle(MyFSMContext *context, const Event &event) override {
    if (event.type == "zattiriko") {
      return new Run();
    }
    return nullptr; // Stay in current state
  }

  std::string getName() const override { return "Init"; }
};

// State2 State
class Run : public MyFSMStateBase {
public:
  void onEntry(MyFSMContext *context) override {
    // Entry action for State2
  }

  void onExit(MyFSMContext *context) override {
    // Exit action for State2
  }

  MyFSMStateBase *handle(MyFSMContext *context, const Event &event) override {
    // No transitions defined
    return nullptr; // Stay in current state
  }

  std::string getName() const override { return "Run"; }
};

// FSM Context Manager
class MyFSMContext {
private:
  MyFSMStateBase *currentState;

public:
  MyFSMContext() { currentState = nullptr; }

  ~MyFSMContext() { delete currentState; }

  void processEvent(const Event &event) {
    if (currentState) {
      MyFSMStateBase *newState = currentState->handle(this, event);
      if (newState) {
        currentState->onExit(this);
        delete currentState;
        currentState = newState;
        currentState->onEntry(this);
      }
    }
  }

  std::string getCurrentStateName() const {
    return currentState ? currentState->getName() : "None";
  }
};

// Usage Example:
// MyFSMContext fsm;
// Event evt{"EVENT_NAME"};
// fsm.processEvent(evt);
